---
title: "Washington State Rental Market"
author: "Anti-code Group"
date: "10/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3)
```

```{r basicfcn}
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```

```{r base_lib}
loadPkg("dplyr")
loadPkg("tidyr")ß
loadPkg("tidyverse")
loadPkg("ggplot2")
loadPkg('ggmap')
loadPkg('rjson')
loadPkg('jsonlite')
loadPkg('leaflet')
loadPkg('RCurl')
```

## Description Data
```{r data}
rents <- read.csv('kc_house_data.csv')
str(rents)
```

```{r geo, echo=FALSE}
qpal <-  colorQuantile(palette = 'GnBu', domain = rents$price, n = 9)
rent.map <- leaflet(rents) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(lng = ~long, lat = ~lat, 
                   stroke = FALSE, 
                   fillOpacity = 5, 
                   color = ~qpal(price), 
                   radius = 5,
                   label = ~as.character(paste0('Price: ', price, ", ", 'condition: ', condition, ", ", 'year built: ', yr_built))) %>%
  addLegend('bottomright', pal = qpal, values = ~price, opacity = 1, title = 'Price Quantiles') #labFormat = labelFormat(prefix = '$')

rent.map
```


```{r zipmap}


```





